name: ncs1-paper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - jupyter
  - notebook
  - jupyterlab
  - pip
  - pip:
      - rdkit